blog_app:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: /blog
        index_tags: [ '-personal' ]

basic_app:
    class: Statocles::App::Basic
    args:
        store: '.'
        url_root: '/'

site:
    class: Statocles::Site
    on:
        - build:
            $class: Statocles::Plugin::LinkCheck
            $args:
                ignore:
                    - '/statocles'
                    - '/yertl'
            $sub: check_pages
    args:
        title: preaction
        base_url: http://preaction.me
        theme: 'theme'
        nav:
            main:
                - title: Blog
                  href: /index.html
                - title: Resume
                  href: /resume
                - title: Talks
                  href: /talks
                - title: Statocles
                  href: /statocles
                - title: Yertl
                  href: /yertl
                - title: Food
                  href: http://indiepalate.com
        deploy: 
            $class: Statocles::Deploy::Git
            $args:
                path: '.'
                branch: deploy
                remote: deploy
        index: /blog
        apps:
            blog:
                $ref: blog_app
            basic:
                $ref: basic_app

        plugins:
            highlight:
                $class: Statocles::Plugin::Highlight
                $args:
                    style: solarized-light
        data:
            google_analytics_id: 'UA-61295159-2'
            disqus:
                shortname: preaction
